#!/bin/bash
set -euo pipefail

: "${BOT_USER:?BOT_USER not set — source .env}"
: "${GIT_USER_NAME:?GIT_USER_NAME not set — source .env}"
: "${GIT_USER_EMAIL:?GIT_USER_EMAIL not set — source .env}"
: "${CERT_DIR:?CERT_DIR not set — source .env}"
: "${CERT_FILE:?CERT_FILE not set — source .env}"
: "${CERT_KEY_FILE:?CERT_KEY_FILE not set — source .env}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
DOTFILES_DIR="$REPO_DIR/dotfiles"

BOT_HOME="/Users/$BOT_USER"

echo "Deploying dotfiles for '$BOT_USER'..."

deploy_dotfile() {
  local src="$1"
  local dest="$2"

  if [ -f "$dest" ] && [ ! -L "$dest" ]; then
    echo "  Backing up existing $dest to ${dest}.bak"
    sudo -u "$BOT_USER" cp "$dest" "${dest}.bak"
  fi

  sudo -u "$BOT_USER" ln -sf "$src" "$dest"
  echo "  Linked $dest -> $src"
}

deploy_dotfile "$DOTFILES_DIR/zshrc"    "$BOT_HOME/.zshrc"
deploy_dotfile "$DOTFILES_DIR/gitconfig" "$BOT_HOME/.gitconfig"
deploy_dotfile "$DOTFILES_DIR/tmux.conf" "$BOT_HOME/.tmux.conf"

# Set git identity for the bot user
sudo -u "$BOT_USER" git config --global user.name "$GIT_USER_NAME"
sudo -u "$BOT_USER" git config --global user.email "$GIT_USER_EMAIL"

# Write .botenv with cert paths (sourced by .zshrc)
BOTENV="$BOT_HOME/.botenv"
cat <<ENVEOF | sudo -u "$BOT_USER" tee "$BOTENV" > /dev/null
# Generated by achan-bot.local setup — do not edit manually
export LOCALHOST_CERT="\$HOME/$CERT_DIR/$CERT_FILE"
export LOCALHOST_KEY="\$HOME/$CERT_DIR/$CERT_KEY_FILE"
ENVEOF
echo "  Wrote $BOTENV"

echo "Dotfiles deployed."
